package view;

import javafx.fxml.FXML;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;

import view.CambiarEscena;

public class MainViewController {
	private CambiarEscena adminEsena = new CambiarEscena();
	@FXML
	private JFXButton ResidenteNAV;
	@FXML
	private JFXButton AgregarResidentesNAV;
	@FXML
	private JFXButton AddMedicineNAV;
	@FXML
	private JFXButton SubMedNAV;
	@FXML
	private JFXButton btnVerPersona;

	// Event Listener on JFXButton[#ResidenteNAV].onAction
	@FXML
	public void loadResidentes(ActionEvent event) {
		adminEsena.loadResidentes();
	}
	// Event Listener on JFXButton[#AgregarResidentesNAV].onAction
	@FXML
	public void loadAddResidente(ActionEvent event) {
		adminEsena.addResidente();
	}
	// Event Listener on JFXButton[#AddMedicineNAV].onAction
	@FXML
	public void loadAddMedicine(ActionEvent event) {
		adminEsena.addMedicamento();
	}
	// Event Listener on JFXButton[#SubMedNAV].onAction
	@FXML
	public void loadSubMed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#btnVerPersona].onAction
	@FXML
	public void loadPersona(ActionEvent event) {
		adminEsena.viewPerfil();
	}
}
